from car import Car
car1=Car("Tesla",2023,"Black",False)
car2=Car("Aude",2024,"Red",True)

print("***car1***")
print(car1.model)
print(car1.year)
print(car1.color)
print(car1.for_sale)
print("***car2***")
print(car2.model)
print(car2.year)
print(car2.color)
print(car2.for_sale)
print("\n")
car1.drive()
car1.stop()
car2.drive()
car2.stop()

car1.description()
car2.description()
